### ISSUE TITLE
Cleanup from template use

### ISSUE THREAD

**Issue by tteltrab** [tsg1204/PortfolioGrita#1]
It's pretty obvious as is that you used a template, which isn't a bad thing. You'll just want to go through and clean up the existing code to make it non-obvious that you used a template in the creation of the site. Lines like https://github.com/tsg1204/PortfolioGrita/blob/master/index.html#L444

alluding to a "Free Trial" are somewhat damning :)

**Comment by tsg1204** [comment]
done
