### ISSUE TITLE
Suggestion: Use first person instead of third person

### ISSUE THREAD

**Issue by tteltrab** [tsg1204/PortfolioGrita#3]
Use "I'm currently a software" Don't say "Tatiana was born and raised, say "I was born and raised". "My career began..."

Strange to have a personal site where your bio is in third person; you're introducing them to yourself, but it seems kind of impersonal.

**Comment by tsg1204** [comment]
<p class="text-muted">Currently a software developer with Cotton, Inc., I was born and raised in Russia where I graduated from Smolensk Economic College with a degree in Accounting. My career began with the Center of Statistics as a computer operator where my interest and knowledge of computer programming began.</p>
                            <p class="text-muted">After moving to United States I worked as analyst for West Corp. where I learned the skills of application programming. Later over the years of different employments and volunteer work I was introduced to web development.</p>    
                            <p class="text-muted">Since March 2015 I'm working on maintenance and updates for  a suite of software programs and services that leverage USDA High Volume Instrument (HVI) data, on building new features to add to the system which provides significantly improved cotton inventory management and analysis capabilities, as well as electronic communication between producers, ginners, mills, and merchants/co-ops.</p>

**Comment by tsg1204** [comment]
done
