### ISSUE TITLE
Suggestion: More padding on headers

### ISSUE THREAD

**Issue by tteltrab** [tsg1204/PortfolioGrita#7]
The padding and spacing situation on your site is somewhat strange looking. I'd suggest tweaking/increasing the padding for the heading, and reconsidering the menu experience.

Here's what the page looks like after just having clicked "about":

![image](https://cloud.githubusercontent.com/assets/1487463/22220524/099f9124-e17d-11e6-958e-fc036e214c8f.png)

**Comment by tsg1204** [comment]
"reconsidering the menu experience" Nick not sure what you mean... If I add more padding it will be too much white space, no?

**Comment by tteltrab** [comment]
Not necessarily. The "About" header (and others) at the top is too close to the top of the browser - a little extra padding on the top/bottom might make it look somewhat better.

Re: the menu experience, the side-nav is kind of strange, but not necessarily wrong. It's just a little weird that it overlays the existing content and doesn't collapse on its own, but that's partially personal opinion.

**Comment by tsg1204** [comment]
done
